cohort_CCU = subset(cohort_patients, last_careunit == "CCU")
cohort_CSRU = subset(cohort_patients, last_careunit == "CSRU")
cohort_MICU = subset(cohort_patients, last_careunit == "MICU")
cohort_SICU = subset(cohort_patients, last_careunit == "SICU")
cohort_TSICU = subset(cohort_patients, last_careunit == "TSICU")

nrow(cohort_CCU)
nrow(cohort_CSRU)
nrow(cohort_MICU)
nrow(cohort_SICU)
nrow(cohort_TSICU)

quantile(cohort_CCU$age)
quantile(cohort_CSRU$age)
quantile(cohort_MICU$age)
quantile(cohort_SICU$age)
quantile(cohort_TSICU$age)

table(cohort_CCU$gender)
table(cohort_CCU$gender)/nrow(cohort_CCU)
table(cohort_CSRU$gender)
table(cohort_CSRU$gender)/nrow(cohort_CSRU)
table(cohort_MICU$gender)
table(cohort_MICU$gender)/nrow(cohort_MICU)
table(cohort_SICU$gender)
table(cohort_SICU$gender)/nrow(cohort_SICU)
table(cohort_TSICU$gender)
table(cohort_TSICU$gender)/nrow(cohort_TSICU)

sum(cohort_CCU$benzo>0)
sum(cohort_CCU$benzo>0)/nrow(cohort_CCU)
sum(cohort_CCU$opiod>0)
sum(cohort_CCU$opiod>0)/nrow(cohort_CCU)
sum(cohort_CCU$propofol>0)
sum(cohort_CCU$propofol>0)/nrow(cohort_CCU)
sum(cohort_CCU$precedex>0)
sum(cohort_CCU$precedex>0)/nrow(cohort_CCU)

sum(cohort_CSRU$benzo>0)
sum(cohort_CSRU$benzo>0)/nrow(cohort_CSRU)
sum(cohort_CSRU$opiod>0)
sum(cohort_CSRU$opiod>0)/nrow(cohort_CSRU)
sum(cohort_CSRU$propofol>0)
sum(cohort_CSRU$propofol>0)/nrow(cohort_CSRU)
sum(cohort_CSRU$precedex>0)
sum(cohort_CSRU$precedex>0)/nrow(cohort_CSRU)

sum(cohort_MICU$benzo>0)
sum(cohort_MICU$benzo>0)/nrow(cohort_MICU)
sum(cohort_MICU$opiod>0)
sum(cohort_MICU$opiod>0)/nrow(cohort_MICU)
sum(cohort_MICU$propofol>0)
sum(cohort_MICU$propofol>0)/nrow(cohort_MICU)
sum(cohort_MICU$precedex>0)
sum(cohort_MICU$precedex>0)/nrow(cohort_MICU)

sum(cohort_SICU$benzo>0)
sum(cohort_SICU$benzo>0)/nrow(cohort_SICU)
sum(cohort_SICU$opiod>0)
sum(cohort_SICU$opiod>0)/nrow(cohort_SICU)
sum(cohort_SICU$propofol>0)
sum(cohort_SICU$propofol>0)/nrow(cohort_SICU)
sum(cohort_SICU$precedex>0)
sum(cohort_SICU$precedex>0)/nrow(cohort_SICU)

sum(cohort_TSICU$benzo>0)
sum(cohort_TSICU$benzo>0)/nrow(cohort_TSICU)
sum(cohort_TSICU$opiod>0)
sum(cohort_TSICU$opiod>0)/nrow(cohort_TSICU)
sum(cohort_TSICU$propofol>0)
sum(cohort_TSICU$propofol>0)/nrow(cohort_TSICU)
sum(cohort_TSICU$precedex>0)
sum(cohort_TSICU$precedex>0)/nrow(cohort_TSICU)


quantile(cohort_CCU$duration_hours)/24
quantile(cohort_CSRU$duration_hours)/24
quantile(cohort_MICU$duration_hours)/24
quantile(cohort_SICU$duration_hours)/24
quantile(cohort_TSICU$duration_hours)/24

quantile(cohort_CCU$los)
quantile(cohort_CSRU$los)
quantile(cohort_MICU$los)
quantile(cohort_SICU$los)
quantile(cohort_TSICU$los)

quantile(cohort_CCU$sofa)
quantile(cohort_CSRU$sofa)
quantile(cohort_MICU$sofa)
quantile(cohort_SICU$sofa)
quantile(cohort_TSICU$sofa)
